services:
   palworld:
      image: test/palworld-server-docker:latest
      build: .
      restart: unless-stopped
      container_name: palworld-server
      ports:
        - 8211:8211/udp
        - 27015:27015/udp
      environment:
         - PUID=1000
         - PGID=1000
         - PORT=8211 # Optional but recommended
         - PLAYERS=16 # Optional but recommended
         - MULTITHREADING=true
         - RCON_ENABLED=true
         - RCON_PORT=25575
         - ADMIN_PASSWORD="adminPasswordHere"
         - COMMUNITY=false
         - BACKUP_ENABLED=true
         - DAYS_TO_KEEP=7
         - BACKUP_CRON_EXPRESSION=0 0 * * *
         # Enable the environment variables below if you have COMMUNITY=true
         # - SERVER_PASSWORD="worldofpals"
         # - SERVER_NAME="World of Pals"
      volumes:
         - ./palworld:/palworld/
