---
name: Release
on: # yamllint disable-line rule:truthy
  release:
    types: [published]

jobs:
  # Builds the Dockerfile and pushes it to dockerhub
  release-amd64:
    name: Release - Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker - Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker - Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
          flavor: latest=true

      - name: Docker - Build / Push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  # Builds the Dockerfile.arm64 and pushes it to dockerhub
  release-arm64:
    name: Release - Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker - Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker - Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern=v{{version}}-arm64
            type=semver,pattern=v{{major}}.{{minor}}-arm64
            type=semver,pattern=v{{major}}-arm64
            type=raw,value=latest-arm64
          flavor: latest=false

      - name: Docker - Build / Push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile.arm64
          platforms: linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
