name: Generate Sponsors README
on:
  workflow_dispatch:
  schedule:
    - cron: 45 12 * * *
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Sponsors
        uses: JamesIves/github-sponsors-readme-action@v1
        with:
          token: ${{ secrets.SPONSOR_PAT }}
          file: 'README.md'

      - name: Deploy to README
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: '.'