---
name: Unit-test
on:  # yamllint disable-line rule:truthy
  pull_request:
  workflow_call:
  push:
    branches: [unittest]

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: true

jobs:
  unit-test-amd64:
    name: Docker - Test (amd64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          load: true
          tags: ${{ github.run_id }}
          platforms: linux/amd64

      - name: Run server
        run: |
            docker run -d \
            --name palworld-server \
            -p 8211:8211/udp \
            -p 27015:27015/udp \
            -p 25575:25575/tcp \
            -v ./palworld:/palworld/ \
            --env-file .env.example \
            --restart unless-stopped \
            --stop-timeout 30 \
            ${{ github.run_id }}

      - name: Wait for server to start
        run: |
            TIMEOUT_SECONDS=120
            START_TIME=$(date +%s)

            while ! docker logs palworld-server 2>&1 | grep -q "Setting breakpad minidump AppID"; do
              CURRENT_TIME=$(date +%s)
              ELAPSED_TIME=$((CURRENT_TIME - START_TIME))

              if [ $ELAPSED_TIME -gt $TIMEOUT_SECONDS ]; then
                echo "Timeout reached. Server failed to start within $TIMEOUT_SECONDS seconds."
                printf "\e[0;32m%s\e[0m\n" "*****Container LOGS*****"
                docker logs palworld-server
                exit 1  # or handle the failure accordingly
              fi
            done

      - name: Test if rcon.yaml is valid
        run: |
            RCON_PORT=$(grep "^RCON_PORT=" .env.example | cut -d '=' -f2)
            ADMIN_PASSWORD=$(grep "^ADMIN_PASSWORD=" .env.example | cut -d '=' -f2)

            ADDRESS=$(docker exec palworld-server cat /home/steam/server/rcon.yaml | grep "^  address:" | awk '{print $2}' | tr -d '"')
            PASSWORD=$(docker exec palworld-server cat /home/steam/server/rcon.yaml | grep "^  password:" | awk '{print $2}' | tr -d '"')

            if [ "$RCON_PORT" != "$ADDRESS" ]; then
              echo "Error: $RCON_PORT in .env.example != $ADDRESS in rcon.yaml."
              exit 1
            fi

            if [ "$ADMIN_PASSWORD" != "$PASSWORD" ]; then
              echo "Error: $ADMIN_PASSWORD in .env.example != $PASSWORD in rcon.yaml."
              exit 1
            fi

      - name: Test if rcon works
        run: |
            sleep 5
            if ! docker exec palworld-server rcon-cli Info | grep -q "Welcome to Pal Server"; then
              echo "Server may not have started successfully."
              exit 1
            fi

            OUTPUT=$(docker exec -it palworld-server rcon-cli "Broadcast test" 2>&1)
            if [[ $OUTPUT != *"Broadcasted: test"* ]]; then
              echo "Error: Unexpected output - $OUTPUT"
              exit 1
            fi

            OUTPUT=$(docker exec -it palworld-server rcon-cli save 2>&1)
            if [[ $OUTPUT != *"Complete Save"* ]]; then
              echo "Error: Unexpected output - $OUTPUT"
            fi

      - name: Test if port 8211, 27015 and 25575 are listening
        run: |
            nc -z -u -v 127.0.0.1 8211 || exit 1
            nc -z -u -v 127.0.0.1 27015 || exit 1
            nc -z -v 127.0.0.1 25575 || exit 1

      - name: Test the backup script
        run: |
            docker exec palworld-server backup
            if [ ! -f ./palworld/backups/palworld-save-*.tar.gz ]; then
              echo "Backup file not found. Backup command may have failed."
              exit 1
            fi

      - name: Test if PalWorldSettings.ini is valid
        run: |
            if [ ! -f ./palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini ]; then
              echo "Error: PalWorldSettings.ini file is missing."
              exit 1
            fi

            if ! grep -q "\[\/Script\/Pal.PalGameWorldSettings\]" ./palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini; then
              echo "Error: PalWorldSettings.ini is missing the required section [/Script/Pal.PalGameWorldSettings]."
              exit 1
            fi

            if ! grep -q "^OptionSettings=\(.*\)" ./palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini; then
              echo "Error: PalWorldSettings.ini is missing or has an invalid OptionSettings section."
              exit 1
            fi

  unit-test-arm64:
    name: Docker - Test (arm64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          load: true
          tags: ${{ github.run_id }}:arm64
          platforms: linux/arm64

      - name: Run server
        run: |
            docker run -d \
            --name palworld-server \
            --platform linux/arm64 \
            -p 8211:8211/udp \
            -p 27015:27015/udp \
            -p 25575:25575/tcp \
            -v ./palworld:/palworld/ \
            --env-file .env.example \
            --restart unless-stopped \
            --stop-timeout 30 \
            ${{ github.run_id }}:arm64

      - name: Wait for server to start
        run: |
            TIMEOUT_SECONDS=600
            START_TIME=$(date +%s)

            while ! docker logs palworld-server 2>&1 | grep -q "Setting breakpad minidump AppID"; do
              CURRENT_TIME=$(date +%s)
              ELAPSED_TIME=$((CURRENT_TIME - START_TIME))

              if [ $ELAPSED_TIME -gt $TIMEOUT_SECONDS ]; then
                echo "Timeout reached. Server failed to start within $TIMEOUT_SECONDS seconds."
                printf "\e[0;32m%s\e[0m\n" "*****Container LOGS*****"
                docker logs palworld-server
                exit 1  # or handle the failure accordingly
              fi
            done

            printf "\e[0;32m%s\e[0m\n" "*****Container LOGS*****"
            docker logs palworld-server

      - name: Test if rcon.yaml is valid
        run: |
            RCON_PORT=$(grep "^RCON_PORT=" .env.example | cut -d '=' -f2)
            ADMIN_PASSWORD=$(grep "^ADMIN_PASSWORD=" .env.example | cut -d '=' -f2)

            ADDRESS=$(docker exec palworld-server cat /home/steam/server/rcon.yaml | grep "^  address:" | awk '{print $2}' | tr -d '"')
            PASSWORD=$(docker exec palworld-server cat /home/steam/server/rcon.yaml | grep "^  password:" | awk '{print $2}' | tr -d '"')

            if [ "$RCON_PORT" != "$ADDRESS" ]; then
              echo "Error: $RCON_PORT in .env.example != $ADDRESS in rcon.yaml."
              exit 1
            fi

            if [ "$ADMIN_PASSWORD" != "$PASSWORD" ]; then
              echo "Error: $ADMIN_PASSWORD in .env.example != $PASSWORD in rcon.yaml."
              exit 1
            fi

      - name: Test if rcon works
        run: |
            sleep 100
            if ! docker exec palworld-server rcon-cli Info | grep -q "Welcome to Pal Server"; then
              echo "Server may not have started successfully."
              exit 1
            fi

            OUTPUT=$(docker exec -it palworld-server rcon-cli "Broadcast test" 2>&1)
            if [[ $OUTPUT != *"Broadcasted: test"* ]]; then
              echo "Error: Unexpected output - $OUTPUT"
              exit 1
            fi

            OUTPUT=$(docker exec -it palworld-server rcon-cli save 2>&1)
            if [[ $OUTPUT != *"Complete Save"* ]]; then
              echo "Error: Unexpected output - $OUTPUT"
            fi

      - name: Test if port 8211, 27015 and 25575 are listening
        run: |
            nc -z -u -v 127.0.0.1 8211 || exit 1
            nc -z -u -v 127.0.0.1 27015 || exit 1
            nc -z -v 127.0.0.1 25575 || exit 1

      - name: Test the backup script
        run: |
            docker exec palworld-server backup
            if [ ! -f ./palworld/backups/palworld-save-*.tar.gz ]; then
              echo "Backup file not found. Backup command may have failed."
              exit 1
            fi

      - name: Test if PalWorldSettings.ini is valid
        run: |
            if [ ! -f ./palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini ]; then
              echo "Error: PalWorldSettings.ini file is missing."
              exit 1
            fi

            if ! grep -q "\[\/Script\/Pal.PalGameWorldSettings\]" ./palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini; then
              echo "Error: PalWorldSettings.ini is missing the required section [/Script/Pal.PalGameWorldSettings]."
              exit 1
            fi

            if ! grep -q "^OptionSettings=\(.*\)" ./palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini; then
              echo "Error: PalWorldSettings.ini is missing or has an invalid OptionSettings section."
              exit 1
            fi
